version: "3.9"
services:
  web:
    build: example
    ports:
      - "8080:5000"
    platform: linux/amd64
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - './example/init.sql:/docker-entrypoint-initdb.d/init.sql'
